### PR TITLE
Add option for shell executer

### PR DESCRIPTION
**Pull request by arc279**
take over environment variables from parent process.

To need ENV from parent when mounted as rails engine.

### CODE REVIEW

**Comment by eisuke** [comment]
@arc279 Can you please tell me the use case for this request? I think that it will be solved on the shell command side (i.e dotenv gem and so on)

**Comment by arc279** [comment]
@eisuke 

Our rails app mounts kuroko2 like this,

```routes.rb
mount Kuroko2::Engine => '/kuroko2'
```

and, settings are in `config/application.yml` as using [Figaro](https://github.com/laserlemon/figaro), but not like dotenv.

We need main app's ENV(via application.yml) for kuroko2's custom tasks.

**Comment by eisuke** [comment]
> We need main app's ENV(via application.yml) for kuroko2's scripts.

The `command-executor` which executes the shell command is started by a process different from the Rails application which mounted kuroko2 engine.  Therefore the mounted path does not matter.

And I think that the environment variable should be loaded on by the executed command side.
For example, if you use the `rake` command or `rails runner` in kuroko2 `execute` task, environment variables that configured by `config/application.yml` should be loaded.  The Figaro gem should not be an exception.

If what I pointed out is wrong, Can I see your actual kuroko2 script?

**Comment by arc279** [comment]
@eisuke 

We use [bricolage](https://github.com/bricolages/bricolage) for aws redshift's manipulations,
and kuroko2 script like this,

```
execute: bundle exec bricolage -e development  --job lib/bricolage/path/to.job --variable=foo=bar
```
but unfortunately, `bricolage` command can't load main app's `config/application.yml`.

I thought of using kuroko2's `env` task instead,
but abandoned for reason that secret variables expand and insert into script(like `aws_secret_key`).

We want to pass main app's ENV while keeping it hidden.

**Comment by eisuke** [comment]
@arc279 

Thank you for sharing your kuroko2 script. I understood your situation.
But I think it is not a responsibility of kuroko2 command-executor (
I think that executed process and command-executor process should be independent. Even `cron` and `systemd` do not pass all environment variables).  

It seems better to wrap the bricolage command from your main rails application, Like `bundle exec your_main_rails_app_path/bin/bricolage_runner.rb [options]`, Or 
use Rails-independent environment variable management system.

**Comment by arc279** [comment]
@eisuke

OK, we will adopt dotenv instead of Figaro in our app, and `source .env` before bricolage command.
Thanks for your advice.

**Pull request closed without merging**
