### PR TITLE
Delete tag feature

### PR DESCRIPTION
**Pull request by mozamimy**
This patch enables to delete tags by clicking ✕ sign.

Review please! @cookpad/dev-infra 

# Screen capture

The capture shows only dashboard view, but this feature also available in job definitions view and user view.

### CODE REVIEW

**Comment by makimoto** [comment]
I worry that a user removes a tag used by other users.

**Comment by eisuke** [comment]
> I worry that a user removes a tag used by other users.

I think same too.

@mozamimy 
I feel that deleting a tag action effects large range.
If I accidentally delete the popular tag, How to undo?

I suggest

* Make a new tag list page, and deletable on that page only.
* Cannot delete tags what has been related by jobs.

WDYT?

**Comment by mozamimy** [comment]
> I worry that a user removes a tag used by other users.

That's right, and @eisuke 's two suggestions protect from accidental tag deletion.
I think first suggestion will be good because,

- **Consistency**: Also tags should have CRUD interface like other resources (job definitions, users, etc.)
-  **View Design**: Of course tags that don't have related job definitions are be with ✕ sign, but It's difficult to handle other tags.

What do you think? I want more opinions.
I'll change this implementation according this discussion 🐰

**Comment by eisuke** [comment]
I have yet another suggestions.
Ideally, We don't want to manage tags. We want automatically deleting unused tags.

* Create a deleting unused tags script managed by kuroko2 itself (like [bin/cleanup_old_instances.rb](https://github.com/mozamimy/kuroko2/blob/6aba9a94740a76eaa1a5e0e762f94e12047217af/bin/cleanup_old_instances.rb) ).
* Check references and delete unused tags when job definition's tag field is edited.

How about doing either or both these?

**Comment by mozamimy** [comment]
> Ideally, We don't want to manage tags.

Yes, the original motivation that I wrote this patch was to delete unnecessary tags.

So I'll send another PR that contains deleting unused tags script and checking tags during updating job definitions.

**Pull request closed without merging**
