### PR TITLE
Add acknowledgements

### PR DESCRIPTION
**Pull request by takai**

### CODE REVIEW

**Comment by sorah** [comment]
How about adding yourself in `gem.authors`?

**Comment by takai** [comment]
It doesn't not bad.

**Comment by ryotarai** [comment]
s/originaly/originally/ ?

**Comment by takai** [comment]
Added. Please review again.

**Comment by adorechic** [comment]
:+1:

**Comment by k0kubun** [comment]
:+1:

**Comment by eisuke** [comment]
LGTM

**Pull request merged**
