### PR TITLE
Exclude eager loading kuroko2/engine.rb

### PR DESCRIPTION
**Pull request by eisuke**
After applying issue https://github.com/cookpad/kuroko2/pull/2, An  `<class:Engine>': can't modify frozen Array (RuntimeError)` error occurred in the my development enviroment that is setting `config.eager_load = true` and `config.cache_classes = fase`.

The full error trace is https://gist.github.com/eisuke/fe3e903b175110e768f4f95859c7a627.

The cause is loading the `Kuroko2::Engine` twice in eager loading and initializing mountable engine. So I change to using `eager_load_namespaces`  and exclude loading `Kuroko2::Engine` while eager loading.

The `eager_load!` implementation is in reference to https://github.com/rails/rails/blob/56b3849316b9c4cf4423ef8de30cbdc1b7e0f7af/railties/lib/rails/engine.rb#L472-L479

Please review @cookpad/dev-infra 
cc: @hogelog

### CODE REVIEW

**Comment by eagletmt** [comment]
How about splitting the directory?
`lib/autoload` is for autoloading and eager-loading, and `lib` is for other modules which requires explicit `require` .

```ruby
config.autoload_paths << root.join('lib/autoload')
config.eager_load_paths << root.join('lib/autoload')
```

**Comment by k0kubun** [comment]
+1 for splitting the directory. Now kuroko2 is not a Rails app but a gem and there are some code to require lib/*.rb.

**Comment by eisuke** [comment]
@eagletmt @k0kubun Thank you for your opinion. Looks good splitting the directory.  d70ceac

**Comment by adorechic** [comment]
LGTM

**Comment by k0kubun** [comment]
LGTM

**Pull request merged**
